[package]
name = "wasip122"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
wasi-preview1-component-adapter-provider = "36.0.2"
wit-component = "0.238.1"
